export const virtualCards = [
    {
        postedTime: '1', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Exclusive Updates',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '2', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Exclusive Updates',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '3', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Exclusive Updates',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '4', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Exclusive Updates',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '5', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Exclusive Updates',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '6', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Latest Updates',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/keerthi.jpg?alt=media&token=f0646080-a625-449b-8696-294c138ad58b',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '7', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Latest Updates',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/keerthi.jpg?alt=media&token=f0646080-a625-449b-8696-294c138ad58b',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '8', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Latest Updates',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/keerthi.jpg?alt=media&token=f0646080-a625-449b-8696-294c138ad58b',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '9', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Latest Updates',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/keerthi.jpg?alt=media&token=f0646080-a625-449b-8696-294c138ad58b',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '10', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Latest Updates',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/nani1.jpg?alt=media&token=d51cd467-b1f0-461e-aeb8-5a9c02e1129e',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '11', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Latest Buzz',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/nani1.jpg?alt=media&token=d51cd467-b1f0-461e-aeb8-5a9c02e1129e',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '12', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Latest Buzz',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/nani1.jpg?alt=media&token=d51cd467-b1f0-461e-aeb8-5a9c02e1129e',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '13', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Latest Buzz',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/nani1.jpg?alt=media&token=d51cd467-b1f0-461e-aeb8-5a9c02e1129e',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '14', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Latest Buzz',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/nani1.jpg?alt=media&token=d51cd467-b1f0-461e-aeb8-5a9c02e1129e',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '15', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Latest Buzz',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/nani1.jpg?alt=media&token=d51cd467-b1f0-461e-aeb8-5a9c02e1129e',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '16', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Reviews',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '17', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Reviews',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '18', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Reviews',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '19', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Reviews',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '20', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Reviews',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '21', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Suggestions',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '22', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Suggestions',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '23', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Suggestions',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '24', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Suggestions',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '25', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Suggestions',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '26', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Box Office Collections',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '27', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Box Office Collections',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '28', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Box Office Collections',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '29', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Box Office Collections',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
    {
        postedTime: '30', 
        title:  'Dasara Trailer Launched watch the viewers reaction',
        description : `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        postType: 'Box Office Collections',
        imageURL: 'https://firebasestorage.googleapis.com/v0/b/movies-for-you-official.appspot.com/o/posts%2Fnani.jpg?alt=media&token=137983f7-1980-430d-8df9-7bb10f95bf99',
        videoURL: '',
        imageTitle: 'Nani from Dasara movie' ,
        writtenBy: 'Rakesh',
        yearOfRelease: '2023'
    },
];